apiVersion: v1
kind: Service
metadata:
  name: go-ecommerce-app-service
  namespace: go-ecommerce
spec:
  selector:
    app: go-ecommerce
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort