apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: go-ecommerce
type: Opaque 
stringData:
  POSTGRES_USER: ${POSTGRES_USER:-test}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test}
  POSTGRES_DB: ${POSTGRES_DB:-test}