name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 

    - name: Set up Go environment
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.4'
        cache: true

    - name: Download Go modules
      run: go mod download

    - name: Run all tests (including handlers/tests)
  
      run: go test -v ./...